export type GlossaryEntry = { term: string; definition: string };

export const glossary: GlossaryEntry[] = [
  { term: "DOF", definition: "A coordinate needed to describe an independent motion." },
  { term: "Natural frequency", definition: "The frequency at which a system vibrates in free motion for a selected mode." },
  { term: "Angular frequency", definition: "Frequency measured in radians per second, ω=2πf." },
  { term: "Period", definition: "Time for one cycle, T=1/f." },
  { term: "Damping coefficient", definition: "Viscous force coefficient c in Fd=−cẋ." },
  { term: "Damping ratio", definition: "Dimensionless damping measure ζ relative to critical damping." },
  { term: "Critical damping", definition: "The boundary between oscillatory and non-oscillatory free response." },
  { term: "Mode", definition: "A natural frequency together with its associated spatial pattern." },
  { term: "Mode shape", definition: "Relative modal coordinates; its scale is a representation choice." },
  { term: "Eigenvalue", definition: "The modal value λ=ω² in the generalized eigenproblem." },
  { term: "Eigenvector", definition: "The vector φ that supplies a mode shape." },
  { term: "Normalization", definition: "Scaling a mode vector without changing its relative pattern." },
  { term: "Orthogonality", definition: "Independence of modes under the mass and stiffness inner products." },
  { term: "Modal coordinate", definition: "The time-varying coordinate q for a modal basis." },
  { term: "Modal superposition", definition: "Building physical motion from weighted modal patterns." },
  { term: "FRF", definition: "Frequency response function mapping harmonic input to output." },
  { term: "Resonance", definition: "Large forced response when excitation is near a system-sensitive frequency." },
  { term: "Phase", definition: "Relative timing angle between harmonic input and output." },
  { term: "Participation factor", definition: "Γᵢ measuring how an influence direction projects onto mode i." },
  { term: "Effective modal mass", definition: "Mass contribution of a mode for a specified excitation direction." },
  { term: "Rigid-body mode", definition: "A zero-strain free-free mode with approximately zero frequency." },
  { term: "Response spectrum", definition: "Peak oscillator response across periods for one record and damping." },
  { term: "PSD", definition: "Power spectral density describing stochastic power or variance by frequency." },
  { term: "RMS", definition: "Root mean square, a measure of stochastic response magnitude." },
  { term: "FEM", definition: "Finite element method, assembling local element models into a global model." },
  { term: "Element", definition: "A finite subdomain with local nodes and local matrices." },
  { term: "Node", definition: "A finite element location carrying one or more degrees of freedom." },
  { term: "Boundary condition", definition: "A constraint or prescribed motion applied to selected degrees of freedom." },
];
